FROM golang:1.15 as builder

ENV GOCRON_VERSION=1.5.3
ENV GOCRON_SOURCE_DOWNLOAD_URL=https://github.com/ouqiang/gocron/archive/refs/tags/v${GOCRON_VERSION}.tar.gz
ENV GOCRON_DOWNLOAD_URL=https://github.com/ouqiang/gocron/releases/download/v${GOCRON_VERSION}/gocron-node-v${GOCRON_VERSION}-linux-amd64.tar.gz
ENV GOCRON_NODE_DOWNLOAD_URL=https://github.com/ouqiang/gocron/releases/download/v${GOCRON_VERSION}/gocron-v${GOCRON_VERSION}-linux-amd64.tar.gz
ENV CERTSTRAP_VERSION=1.2.0
ENV CERTSTRAP_DOWNLOAD_URL=https://github.com/square/certstrap/releases/download/v${CERTSTRAP_VERSION}/certstrap-${CERTSTRAP_VERSION}-linux-amd64

WORKDIR /tmp
RUN set -ex; \
	apt-get update; \
	apt-get install -y \
	nodejs npm \
	; \
	apt-get remove cmdtest; \
	npm install -g yarn; \
	git clone https://github.com/up9cloud/gocron.git; \
	# git checkout tags/v${GOCRON_VERSION}; \
	# curl -sSL ${GOCRON_SOURCE_DOWNLOAD_URL} -o gocron.tar.gz; \
	# tar -xvf gocron.tar.gz; \
	cd gocron
