${TEMPLATE_0}
${TEMPLATE_1}
${TEMPLATE_2}

FROM scratch

# COPY --from=builder /tmp/gocron-linux-amd64/gocron /gocron/gocron
COPY --from=builder /tmp/gocron/bin/gocron /gocron/gocron

WORKDIR /gocron
VOLUME [ "/gocron/conf", "/gocron/log", "/gocron/out" ]
EXPOSE 5920
CMD [ "./gocron", "web" ]
